version: "2"

services:
    lemp-mariadb:
        image: mariadb:latest
        container_name: lemp-mariadb
        volumes:
            - ./lemp-volume-mariadb:/var/lib/mysql
        networks:
            - lemp-network
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    lemp-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lemp-phpmyadmin
        networks:
            - lemp-network
        ports:
            - "8183:80"
        environment:
            PMA_ARBITRARY: 1
        links:
            - lemp-mariadb

networks:
    lemp-network:
        driver: bridge
